# Quick Start Guide

NOTE: `This is the CompuLab Warrior release candidate.`

# Supported CompuLab Machines
* `cl-som-imx7`

# Prepare NXP BSP
[source,console]
repo init -u git://source.codeaurora.org/external/imx/imx-manifest.git -b imx-linux-warrior -m imx-4.19.35-1.1.0.xml
repo sync

# Download CompuLab meta layer
[source,console]
git clone -b devel-warrior https://github.com/compulab-yokneam/meta-bsp-imx7.git sources/meta-bsp-imx7/

# Set COMPULAB_MACHINE environment variable
* `cl-som-imx7`
[source,console]
COMPULAB_MACHINE=cl-som-imx7

# Build Images
Refer to the https://source.codeaurora.org/external/imx/meta-fsl-bsp-release/tree/imx/README?h=warrior-4.19.35-1.1.0[`NXP Readme`] for details about how to select a correct `backend` & `distro`.

* Minimal core image
[source,console]
MACHINE=${COMPULAB_MACHINE} DISTRO=fsl-imx-fb source sources/meta-bsp-imx7/tools/setup-env -b build-fb-imx7
bitbake -k core-image-minimal

* Full command line core image
[source,console]
MACHINE=${COMPULAB_MACHINE} DISTRO=fsl-imx-fb source sources/meta-bsp-imx7/tools/setup-env -b build-fb-imx7
bitbake -k core-image-full-cmdline

* Weston GUI image
[source,console]
MACHINE=${COMPULAB_MACHINE} DISTRO=fsl-imx-xwayland source sources/meta-bsp-imx7/tools/setup-env -b build-xwayland-imx7
bitbake -k fsl-image-validation-imx

* Weston GUI image with Qt5 support
[source,console]
MACHINE=${COMPULAB_MACHINE} DISTRO=fsl-imx-xwayland source sources/meta-bsp-imx7/tools/setup-env -b build-xwayland-imx7
bitbake -k fsl-image-qt5-validation-imx

* XFCE GUI image
[source,console]
MACHINE=${COMPULAB_MACHINE} DISTRO=fsl-imx-x11 source sources/meta-bsp-imx7/tools/setup-env -b build-x11-imx7
bitbake -k compulab-image-xfce

# Build U-boot only:
* Issue the configuration script with the minimal configuration. The configuration script will ask about U-Boot version (2017.07|2018.11), please choose the one required:
[source,console]
MACHINE=${COMPULAB_MACHINE} DISTRO=fsl-imx-fb source sources/meta-bsp-imx7/tools/setup-env -b build-fb-imx7

* Issue the U-boot build:
[source,console]
bitbake -k u-boot-compulab

* Result is at:
[source,console]
ls ${BUILDDIR}/tmp/deploy/images/${MACHINE}/u-boot.imx

# Build results
* The results of the build can be found at `${BUILDDIR}/tmp/deploy/images/${COMPULAB_MACHINE}`
[source,console]
ls -ltr ${BUILDDIR}/tmp/deploy/images/${COMPULAB_MACHINE}

* Images files
SD-card images files compressed by `xz` and can be listed this way:
[source,console]
ls -ltr ${BUILDDIR}/tmp/deploy/images/${COMPULAB_MACHINE}/*.sdcard.*

# Create bootable media
NOTE: In this chapter the target block device `/dev/sdi` is just an example.
Make use ot the development host device name instead.

## Using `dd`
[source,console]
cd ${BUILDDIR}/tmp/deploy/images/${COMPULAB_MACHINE}
sudo dd bs=1M status=progress if=compulab-image-xfce-cl-som-imx7.wic.xz of=/dev/sdi

## Using `bmaptool`
[source,console]
cd ${BUILDDIR}/tmp/deploy/images/${COMPULAB_MACHINE}
sudo bmaptool copy compulab-image-xfce-cl-som-imx7.wic.xz --bmap compulab-image-xfce-cl-som-imx7.wic.bmap /dev/sdi

# Device Trees and available features
## sbc-imx7
* imx7d-sbc-imx7.dtb -- U-Boot default
* imx7d-sbc-imx7-lvds.dtb -- LVDS on
* imx7d-sbc-imx7-m4.dtb -- M4 tests ready

## sbc-iot-imx7
* imx7d-sbc-iot-imx7.dtb
* imx7d-sbc-iot-imx7-can.dtb -- CAN on
* imx7d-sbc-iot-imx7-rs485-hdx.dtb - rs485 on
