# Quick Start Guide

# Supported CompuLab Machines
* `cl-som-imx7`

# Setup Yocto environment
* WorkDir:
[source,console]
mkdir compulab-nxp-bsp-imx7 && cd compulab-nxp-bsp-imx7

* Set a CompuLab machine:
|=======================
|Machine|Command Line
|cl-som-imx7|```export COMPULAB_MACHINE=cl-som-imx7```
|=======================

* Download and run main script:
[source,console]
wget https://raw.githubusercontent.com/compulab-yokneam/meta-bsp-imx7/warrior/tools/runme.sh
chmod +x ./runme.sh
./runme.sh

# Build Images
Refer to the https://github.com/nxp-imx/meta-fsl-bsp-release/blob/warrior-4.19.35-1.1.0/imx/README[`NXP Readme`] for details about how to select a correct `backend` & `distro`.

* Minimal core image
[source,console]
MACHINE=${COMPULAB_MACHINE} DISTRO=fsl-imx-fb source sources/meta-bsp-imx7/tools/setup-env -b build-fb-imx7
bitbake -k core-image-minimal

* Full command line core image
[source,console]
MACHINE=${COMPULAB_MACHINE} DISTRO=fsl-imx-fb source sources/meta-bsp-imx7/tools/setup-env -b build-fb-imx7
bitbake -k core-image-full-cmdline

* Weston GUI image
[source,console]
MACHINE=${COMPULAB_MACHINE} DISTRO=fsl-imx-xwayland source sources/meta-bsp-imx7/tools/setup-env -b build-xwayland-imx7
bitbake -k fsl-image-validation-imx

* Weston GUI image with Qt5 support
[source,console]
MACHINE=${COMPULAB_MACHINE} DISTRO=fsl-imx-xwayland source sources/meta-bsp-imx7/tools/setup-env -b build-xwayland-imx7
bitbake -k fsl-image-qt5-validation-imx

* XFCE GUI image
[source,console]
MACHINE=${COMPULAB_MACHINE} DISTRO=fsl-imx-x11 source sources/meta-bsp-imx7/tools/setup-env -b build-x11-imx7
bitbake -k compulab-image-xfce

# Build results
* The results of the build can be found at `${BUILDDIR}/tmp/deploy/images/${COMPULAB_MACHINE}`
[source,console]
ls -ltr ${BUILDDIR}/tmp/deploy/images/${COMPULAB_MACHINE}

* Images files
SD-card images files compressed by `xz` and can be listed this way:
[source,console]
ls -ltr ${BUILDDIR}/tmp/deploy/images/${COMPULAB_MACHINE}/*.sdcard.*

# Create bootable media
NOTE: In this chapter the target block device `/dev/sdi` is just an example.
Make use ot the development host device name instead.

## Using `dd`
[source,console]
cd ${BUILDDIR}/tmp/deploy/images/${COMPULAB_MACHINE}
sudo dd bs=1M status=progress if=compulab-image-xfce-cl-som-imx7.wic.xz of=/dev/sdi

## Using `bmaptool`
[source,console]
cd ${BUILDDIR}/tmp/deploy/images/${COMPULAB_MACHINE}
sudo bmaptool copy compulab-image-xfce-cl-som-imx7.wic.xz --bmap compulab-image-xfce-cl-som-imx7.wic.bmap /dev/sdi

# Device Trees and available features
## sbc-imx7
* imx7d-sbc-imx7.dtb -- U-Boot default
* imx7d-sbc-imx7-lvds.dtb -- LVDS on
* imx7d-sbc-imx7-m4.dtb -- M4 tests ready

## sbc-iot-imx7
* imx7d-sbc-iot-imx7.dtb
* imx7d-sbc-iot-imx7-can.dtb -- CAN on
* imx7d-sbc-iot-imx7-rs485-hdx.dtb - rs485 on
