# Quick Start Guide

NOTE: This is a development branch is not released/supported officially by CompuLab yet.

# Supported CompuLab Machines
* `cl-som-imx7`

# Setup Yocto environment
* WorkDir
[source,console]
mkdir compulab-bsp && cd compulab-bsp
* Set a CompuLab machine:
[source,console]
export MACHINE=cl-som-imx7

# Initialize repo manifests
* NXP
[source,console]
repo init -u https://github.com/nxp-imx/imx-manifest.git -b imx-linux-kirkstone -m imx-5.15.71-2.2.0.xml
repo sync
* CompuLab
[source,console]
mkdir -p .repo/local_manifests
cd .repo/local_manifests
wget https://raw.githubusercontent.com/compulab-yokneam/meta-bsp-imx7/kirkstone/scripts/meta-bsp-imx7.xml
cd -
* Sync Them all
[source,console]
repo sync
cd .repo/local_manifests
ln -sf ../../sources/meta-bsp-imx7/scripts/meta-bsp-imx7.xml .
cd -

# Setup environment and build image
* Initialize the build environment:
[source,console]
source sources/meta-bsp-imx7/tools/setup-env -b build-${MACHINE}
* Building the image:
[source,console]
bitbake -k imx-image-full

# Create a bootable sd card
NOTE: In this chapter the target block device `/dev/sdi` is just an example.
Make use ot the development host device name instead.

## Using `bmaptool`
[source,console]
cd tmp/deploy/images/${MACHINE}
sudo bmaptool copy imx-image-full-cl-som-imx7.wic.bz2  --bmap imx-image-full-cl-som-imx7.wic.bmap /dev/sdi

# Precompiled images:
[cols="2", options="header"]
|===
|image type
|link

|core
|https://drive.google.com/file/d/1tKg-D33kUpg0_8VDbiFLz86HUAX-JVsI/view?usp=sharing[core-image-minimal-cl-som-imx7-20210811064549.rootfs.wic.bz2]

|imx-image-full
|https://drive.google.com/file/d/1FTRlWW8yrsh8r7hNJfYadKZAWLKGbosa/view?usp=sharing[imx-image-full-cl-som-imx7-20211011093112.rootfs.wic.bz2]
|===
