# Quick Start Guide

NOTE: `This is not an official CompuLab release yet; it is just a development version for Yocto Warrior.`

# Supported CompuLab Machines
* `cl-som-imx7`

# Prepare NXP BSP
[source,console]
repo init -u git://source.codeaurora.org/external/imx/imx-manifest.git -b imx-linux-warrior -m imx-4.19.35-1.1.0.xml
repo sync

# Download CompuLab meta layer
[source,console]
git clone -b devel-warrior https://github.com/compulab-yokneam/meta-bsp-imx7.git sources/meta-bsp-imx7/

# Set a desire machine
* `cl-som-imx7`
[source,console]
COMPULAB_MACHINE=cl-som-imx7

# Build Images
Refer to the https://source.codeaurora.org/external/imx/meta-fsl-bsp-release/tree/imx/README?h=warrior-4.19.35-1.1.0[`NXP Readme`] for details about how to select a correct `backend` & `distro`.

* Minimal core image
[source,console]
MACHINE=${COMPULAB_MACHINE} DISTRO=fsl-imx-fb source sources/meta-bsp-imx7/tools/setup-env -b build-fb-imx7
bitbake -k core-image-minimal

* Full command line core image
[source,console]
MACHINE=${COMPULAB_MACHINE} DISTRO=fsl-imx-fb source sources/meta-bsp-imx7/tools/setup-env -b build-fb-imx7
bitbake -k core-image-full-cmdline

* Weston GUI image
[source,console]
MACHINE=${COMPULAB_MACHINE} DISTRO=fsl-imx-xwayland source sources/meta-bsp-imx7/tools/setup-env -b build-xwayland-imx7
bitbake -k fsl-image-validation-imx

* Weston GUI image with Qt5 support
[source,console]
MACHINE=${COMPULAB_MACHINE} DISTRO=fsl-imx-xwayland source sources/meta-bsp-imx7/tools/setup-env -b build-xwayland-imx7
bitbake -k fsl-image-qt5-validation-imx

* XFCE GUI image
[source,console]
MACHINE=${COMPULAB_MACHINE} DISTRO=fsl-imx-x11 source sources/meta-bsp-imx7/tools/setup-env -b build-x11-imx7
bitbake -k compulab-image-xfce

# Build results
* The results of the build can be found at `${BUILDDIR}/tmp/deploy/images/${COMPULAB_MACHINE}`
[source,console]
ls -ltr ${BUILDDIR}/tmp/deploy/images/${COMPULAB_MACHINE}

* Images files
SD-card images files compressed by `xz` and can be listed this way:
[source,console]
ls -ltr ${BUILDDIR}/tmp/deploy/images/${COMPULAB_MACHINE}/*.sdcard.*
# Sample output
tmp/deploy/images/cl-som-imx7/compulab-image-cl-som-imx7-20200207133104.rootfs.sdcard.xz
tmp/deploy/images/cl-som-imx7/compulab-image-cl-som-imx7.sdcard.xz              
tmp/deploy/images/cl-som-imx7/compulab-image-xfce-cl-som-imx7-20200209074426.rootfs.sdcard.xz
tmp/deploy/images/cl-som-imx7/compulab-image-xfce-cl-som-imx7.sdcard.xz         
tmp/deploy/images/cl-som-imx7/core-image-full-cmdline-cl-som-imx7-20200207181732.rootfs.sdcard.xz
tmp/deploy/images/cl-som-imx7/core-image-full-cmdline-cl-som-imx7.sdcard.xz        
tmp/deploy/images/cl-som-imx7/core-image-minimal-cl-som-imx7-20200204152232.rootfs.sdcard.xz
tmp/deploy/images/cl-som-imx7/core-image-minimal-cl-som-imx7.sdcard.xz          
tmp/deploy/images/cl-som-imx7/fsl-image-qt5-validation-imx-cl-som-imx7-20200208212733.rootfs.sdcard.xz
tmp/deploy/images/cl-som-imx7/fsl-image-qt5-validation-imx-cl-som-imx7.sdcard.xz

# Device Trees and available features
## sbc-imx7
* imx7d-sbc-imx7.dtb -- U-Boot default
* imx7d-sbc-imx7-lvds.dtb -- LVDS on
* imx7d-sbc-imx7-m4.dtb -- M4 tests ready

## sbc-iot-imx7
* imx7d-sbc-iot-imx7.dtb
* imx7d-sbc-iot-imx7-can.dtb -- CAN on
* imx7d-sbc-iot-imx7-rs485-hdx.dtb - rs485 on
