SRC_URI_append_cl-som-imx7 = " \
	file://0000-cl-som-imx7-dts-Update-dts-list.patch \
	file://0001-serial-imx-allow-passing-rs485-options.patch \
	file://0002-ARM-imx7d-clk-select-uart7-clock-parent-and-set-rate.patch \
	file://0003-PCIe-imx6-imx7d-add-support-for-phy-refclk-source-co.patch \
	file://0004-rtc-em3027-correct-month-value.patch \
	file://0005-regulator-userspace-consumer-add-MODULE_ALIAS-macro.patch \
	file://0006-regulator-add-userspace-consumer-wrapper-driver.patch \
	file://0007-ASoC-fsl-add-analog-audio-support-switch-for-imx-boa.patch \
	file://0008-cl-som-imx7-config-Added-the-product-defconfig.patch \
	file://defconfig \
"
