#!/bin/bash -e

MACHINE=${MACHINE:-cl-som-imx7}
DISTRO=${DISTRO:-fsl-imx-x11}
EULA=1
T="../sources/meta-bsp-imx7/templates"

. imx-setup-release.sh $@

for _d in ${T}/*;do
	_file=$(basename ${_d})
	for _f in ${_d}/*;do
		cat ${_f} >> conf/${_file}
	done;
done
